import Head from "next/head";
import Image from "next/image";
import MenuComponent from "../components/Menu";
import HeroComponent from "../components/Hero";
import GettingStartedComponent from "../components/GettingStarted";
import OnDesktopComponent from "../components/OnDesktop";
import PlayerComponent from "../components/Player";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuComponent></MenuComponent>
      <main className={styles.main}></main>

      <div className={`content ${styles.content}`}>
        <HeroComponent></HeroComponent>
        <GettingStartedComponent></GettingStartedComponent>
        <PlayerComponent></PlayerComponent>
        <OnDesktopComponent></OnDesktopComponent>

        <div className={`content__item ${styles.contentItem}`}></div>
        <div
          className={`content__item ${styles.contentItem} ${styles.contentItemFullWidth}`}
        ></div>
      </div>

      <footer className={styles.footer}>
        <a href="pol.dk" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
